// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqvbYChXmwI3rR5SUQ05sEmBIeyfCbNPM',
    appId: '1:1068683024031:android:0931a7fefcfd2fee87b4aa',
    messagingSenderId: '1068683024031',
    projectId: 'hayat-53db2',
    storageBucket: 'hayat-53db2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP8DKf5Uh9V3b6fVWmA8VRXKTsjXAMwhA',
    appId: '1:1068683024031:ios:18e57f7147fa389387b4aa',
    messagingSenderId: '1068683024031',
    projectId: 'hayat-53db2',
    storageBucket: 'hayat-53db2.appspot.com',
    androidClientId:
        '1068683024031-am5v4mttfvg075v6kpqjtf798alte0q3.apps.googleusercontent.com',
    iosClientId:
        '1068683024031-lmf53foklhv0od81v2qan9psgh2k29ot.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled2',
  );
}
